name: DOL/WHD FOH
baseurl: "/dol-whd-foh"
markdown: kramdown

data_source: data

exclude:
- src
- build
- node_modules
- tests
- Gemfile
- Gemfile.lock
- CONTRIBUTING.md
- README.md
- LICENSE.md
- package.json
- run.js
- Staticfile
- manifest.yml

repos:
- name: DOL-WHD-FOH
  description: DOL WHD FOH repo
  url: https://github.com/18F/dol-whd-foh

permalink: "/chapters/:title"

page_gen:
  - data: 'master'
    template: 'chapter'
    name: 'chapter'
    dir: 'chapters'
    
chapters:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 30
  - 31
  - 32
  - 33
  - 36
  - 39
  - 46
